export const Question = [
    {
      prompt: "Which is the capital of England?",
      A: "London",
      B: "Madrid",
      C: "Rome",
      D: "Glasgow",
      answer: "A",
    },
    {
      prompt: "What is the contrary of good?",
      A: "tall",
      B: "thin",
      C: "bad",
      D: "salty",
      answer: "C",
    },
    {
      prompt: "Which planet is known as the Red Planet?",
      A: "Earth",
      B: "Mars",
      C: "Jupiter",
      D: "Saturn",
      answer: "B",
    },
    {
      prompt: "What is the chemical symbol for water?",
      A: "H2O",
      B: "CO2",
      C: "O2",
      D: "NaCl",
      answer: "A",
    },
    {
      prompt: "Who wrote the play 'Romeo and Juliet'?",
      A: "Charles Dickens",
      B: "J.K. Rowling",
      C: "William Shakespeare",
      D: "Mark Twain",
      answer: "C",
    },
    {
      prompt: "What is the largest ocean on Earth?",
      A: "Atlantic Ocean",
      B: "Indian Ocean",
      C: "Arctic Ocean",
      D: "Pacific Ocean",
      answer: "D",
    },
    {
      prompt: "Which country is the largest by land area?",
      A: "USA",
      B: "Russia",
      C: "China",
      D: "Canada",
      answer: "B",
    },
    {
      prompt: "Who painted the Mona Lisa?",
      A: "Vincent van Gogh",
      B: "Pablo Picasso",
      C: "Leonardo da Vinci",
      D: "Claude Monet",
      answer: "C",
    },
    {
      prompt: "What is the tallest mountain in the world?",
      A: "K2",
      B: "Mount Everest",
      C: "Kangchenjunga",
      D: "Lhotse",
      answer: "B",
    },
    {
      prompt: "Which element has the chemical symbol 'O'?",
      A: "Oxygen",
      B: "Gold",
      C: "Iron",
      D: "Silver",
      answer: "A",
    },
    {
      prompt: "Which city is known as 'The Big Apple'?",
      A: "Los Angeles",
      B: "New York",
      C: "Chicago",
      D: "San Francisco",
      answer: "B",
    },
    {
      prompt: "What is the longest river in the world?",
      A: "Amazon",
      B: "Nile",
      C: "Yangtze",
      D: "Mississippi",
      answer: "B",
    },
    {
      prompt: "In which year did World War II end?",
      A: "1942",
      B: "1945",
      C: "1939",
      D: "1918",
      answer: "B",
    },
    {
      prompt: "Which country won the 2018 FIFA World Cup?",
      A: "Brazil",
      B: "Germany",
      C: "France",
      D: "Argentina",
      answer: "C",
    },
    {
      prompt: "Which planet is closest to the Sun?",
      A: "Venus",
      B: "Earth",
      C: "Mercury",
      D: "Mars",
      answer: "C",
    },
    {
      prompt: "Who discovered penicillin?",
      A: "Marie Curie",
      B: "Isaac Newton",
      C: "Alexander Fleming",
      D: "Louis Pasteur",
      answer: "C",
    },
    {
      prompt: "What is the hardest natural substance on Earth?",
      A: "Iron",
      B: "Graphite",
      C: "Diamond",
      D: "Steel",
      answer: "C",
    },
    {
      prompt: "Which is the smallest planet in the Solar System?",
      A: "Mercury",
      B: "Mars",
      C: "Venus",
      D: "Pluto",
      answer: "A",
    },
    {
      prompt: "Which organ pumps blood through the body?",
      A: "Lungs",
      B: "Heart",
      C: "Kidney",
      D: "Brain",
      answer: "B",
    },
    {
      prompt: "Which language is the most spoken worldwide?",
      A: "Spanish",
      B: "English",
      C: "Mandarin Chinese",
      D: "Hindi",
      answer: "C",
    },
    {
      prompt: "What is the largest desert in the world?",
      A: "Sahara",
      B: "Gobi",
      C: "Antarctic",
      D: "Arabian",
      answer: "C",
    },
    {
      prompt: "Who was the first man to step on the Moon?",
      A: "Buzz Aldrin",
      B: "Neil Armstrong",
      C: "Yuri Gagarin",
      D: "John Glenn",
      answer: "B",
    },
    {
      prompt: "Which year did the Titanic sink?",
      A: "1905",
      B: "1912",
      C: "1918",
      D: "1920",
      answer: "B",
    },
    {
      prompt: "What is the capital of Japan?",
      A: "Tokyo",
      B: "Osaka",
      C: "Kyoto",
      D: "Hiroshima",
      answer: "A",
    },
    {
      prompt: "What is the most abundant gas in Earth's atmosphere?",
      A: "Oxygen",
      B: "Hydrogen",
      C: "Nitrogen",
      D: "Carbon dioxide",
      answer: "C",
    },
    {
      prompt: "What is the boiling point of water?",
      A: "50°C",
      B: "100°C",
      C: "150°C",
      D: "200°C",
      answer: "B",
    },
    {
      prompt: "In which country would you find the Eiffel Tower?",
      A: "Spain",
      B: "France",
      C: "Italy",
      D: "Germany",
      answer: "B",
    },
    {
      prompt: "Which animal is known as the 'King of the Jungle'?",
      A: "Tiger",
      B: "Elephant",
      C: "Lion",
      D: "Leopard",
      answer: "C",
    },
    {
      prompt: "What is the largest mammal in the world?",
      A: "Elephant",
      B: "Blue Whale",
      C: "Giraffe",
      D: "Rhino",
      answer: "B",
    },
    {
      prompt: "Which famous scientist introduced the theory of relativity?",
      A: "Isaac Newton",
      B: "Albert Einstein",
      C: "Stephen Hawking",
      D: "Nikola Tesla",
      answer: "B",
    },
    {
      prompt: "What is the capital of Canada?",
      A: "Toronto",
      B: "Ottawa",
      C: "Vancouver",
      D: "Montreal",
      answer: "B",
    },
    {
      prompt: "Which country is known as the Land of the Rising Sun?",
      A: "China",
      B: "Thailand",
      C: "Japan",
      D: "South Korea",
      answer: "C",
    },
    {
      prompt: "Which planet has the most moons?",
      A: "Mars",
      B: "Earth",
      C: "Jupiter",
      D: "Saturn",
      answer: "C",
    },
    {
      prompt: "What is the capital of Australia?",
      A: "Sydney",
      B: "Melbourne",
      C: "Perth",
      D: "Canberra",
      answer: "D",
    },
    {
      prompt: "Which element is necessary for the process of photosynthesis?",
      A: "Hydrogen",
      B: "Carbon dioxide",
      C: "Oxygen",
      D: "Nitrogen",
      answer: "B",
    },
    {
      prompt: "Which European country is divided into cantons?",
      A: "Switzerland",
      B: "Germany",
      C: "France",
      D: "Italy",
      answer: "A",
    },
    {
      prompt: "What is the largest organ in the human body?",
      A: "Heart",
      B: "Skin",
      C: "Lungs",
      D: "Liver",
      answer: "B",
    },
    {
      prompt: "Who invented the telephone?",
      A: "Thomas Edison",
      B: "Alexander Graham Bell",
      C: "Nikola Tesla",
      D: "James Watt",
      answer: "B",
    },
    {
      prompt: "Which country is home to the kangaroo?",
      A: "South Africa",
      B: "Brazil",
      C: "Australia",
      D: "India",
      answer: "C",
    },
    {
      prompt: "What is the smallest country in the world?",
      A: "Monaco",
      B: "Vatican City",
      C: "Liechtenstein",
      D: "San Marino",
      answer: "B",
    },
    {
      prompt: "What is the chemical formula for salt?",
      A: "NaCl",
      B: "H2SO4",
      C: "KCl",
      D: "C6H12O6",
      answer: "A",
    },
    {
      prompt: "Who was the first President of the United States?",
      A: "Abraham Lincoln",
      B: "Thomas Jefferson",
      C: "George Washington",
      D: "John Adams",
      answer: "C",
    },
    {
      prompt: "What is the main language spoken in Brazil?",
      A: "Spanish",
      B: "Portuguese",
      C: "French",
      D: "English",
      answer: "B",
    },
    {
      prompt: "Which country has the largest population?",
      A: "India",
      B: "China",
      C: "USA",
      D: "Russia",
      answer: "B",
    },
    {
      prompt: "Which year did the Berlin Wall fall?",
      A: "1987",
      B: "1989",
      C: "1991",
      D: "1993",
      answer: "B",
    },
    {
      prompt: "Who was the first woman to win a Nobel Prize?",
      A: "Rosalind Franklin",
      B: "Marie Curie",
      C: "Ada Lovelace",
      D: "Jane Goodall",
      answer: "B",
    },
    {
      prompt: "Which U.S. state is known as the 'Sunshine State'?",
      A: "California",
      B: "Texas",
      C: "Florida",
      D: "Hawaii",
      answer: "C",
    }
  ];
  